pipeline {
    agent {
        kubernetes {
            yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: maven-container
    image: maven:3.9.0
    volumeMounts:
    - name: maven-cache
      mountPath: /root/.m2
  - name: git-container
    image: alpine/git:latest
    volumeMounts:
    - name: workspace
      mountPath: /workspace
  volumes:
  - name: maven-cache
    hostPath:
      path: /root/.m2
  - name: workspace
    emptyDir: {}
"""
        }
    }
    stages {
        stage('Build') {
            steps {
                container('maven-container') {
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            steps {
                container('maven-container') {
                    sh 'mvn test'
                }
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                container('maven-container') {
                    sh './jenkins/scripts/deliver.sh'
                }
            }
        }
    }
}
